<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="ProgramSuite" duration-ms="29" started-at="2017-06-19T13:34:43Z" finished-at="2017-06-19T13:34:43Z">
    <groups>
    </groups>
    <test name="ProgramTest" duration-ms="29" started-at="2017-06-19T13:34:43Z" finished-at="2017-06-19T13:34:43Z">
      <class name="testng.SampleProgramTwo">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testng.SampleProgramTwo@12bc6874]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2017-06-19T09:34:43Z" finished-at="2017-06-19T09:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="testOne()[pri:0, instance:testng.SampleProgramTwo@12bc6874]" name="testOne" duration-ms="0" started-at="2017-06-19T09:34:43Z" finished-at="2017-06-19T09:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testng.SampleProgramTwo@12bc6874]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-06-19T09:34:43Z" finished-at="2017-06-19T09:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testng.SampleProgramTwo -->
      <class name="testng.SampleProgramOne">
        <test-method status="PASS" signature="testOne()[pri:0, instance:testng.SampleProgramOne@ba4d54]" name="testOne" duration-ms="6" started-at="2017-06-19T09:34:43Z" finished-at="2017-06-19T09:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="FAIL" signature="testTwo()[pri:0, instance:testng.SampleProgramOne@ba4d54]" name="testTwo" duration-ms="0" started-at="2017-06-19T09:34:43Z" finished-at="2017-06-19T09:34:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [AutomationgTest] but found [AutomationgTesting]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [AutomationgTest] but found [AutomationgTesting]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at testng.SampleProgramOne.testTwo(SampleProgramOne.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at testng.ProgramTestRun.testNgXmlSuite(ProgramTestRun.java:40)
	at testng.ProgramTestRun.main(ProgramTestRun.java:45)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="testThree()[pri:0, instance:testng.SampleProgramOne@ba4d54]" name="testThree" duration-ms="0" started-at="2017-06-19T09:34:43Z" finished-at="2017-06-19T09:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
      </class> <!-- testng.SampleProgramOne -->
    </test> <!-- ProgramTest -->
  </suite> <!-- ProgramSuite -->
</testng-results>
